# # Setup For H2 File
# spring.application.name=demo

# # ✅ File-based H2 DB (saved to ./data/demo-db.mv.db)
# # spring.datasource.url=jdbc:h2:file:./data/demo-db
# spring.datasource.url=jdbc:h2:file:${user.dir}/data/demo-db;AUTO_SERVER=TRUE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# # ✅ JPA + Hibernate
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# # ✅ H2 Web Console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# debug=true

# uncomment for local
# spring.application.name=demo 
# server.port=${PORT:8080}

# # Use Render disk if DB_DIR is set, otherwise use local ./data
# spring.datasource.url=jdbc:h2:file:${DB_DIR:./data}/demo-db;AUTO_SERVER=TRUE

# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# debug=true


# postgres
spring.application.name=demo
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# turn off h2 console (it’s only for h2)
spring.h2.console.enabled=false


